Feature/tj9 jk tdgl
Tareffa/ottimizza-oauth2-server pull request #86
Opened 2020-10-15 20:22 UTC by dmazui

alterada forma de envio de email usando "api email sender"

2020-10-16 12:10 UTC, mtslucasmartins requested changes

2020-10-16 12:10 UTC, mtslucasmartins commented on src/main/java/br/com/ottimizza/application/client/MailSenderClient.java
> +@FeignClient(name = "email-sender-service", url = "https://api-emaiil-sender.herokuapp.com")
Usar variáveis de ambiente, exemplo do outro FeignClient `br.com.ottimizza.application.client.TareffaClient.java`

O ideal é que seja variável de ambiente pra se passarmos a usar o nosso domínio não precisemos alterar o fonte.

2020-10-16 12:10 UTC, mtslucasmartins commented on src/test/resources/application.yml
> +#    url: ${EMAIL_SENDER_URL:https://api-emaiil-sender.herokuapp.com}
Não funcionou por que não passou nos testes ou deu erro? Se não passou nos testes é por que a mesma estrutura deve estar no application.yml do tests.

2020-10-19 17:42 UTC, dmazui commented on src/test/resources/application.yml
> +#    url: ${EMAIL_SENDER_URL:https://api-emaiil-sender.herokuapp.com}
alterei em ambos os yml e não resolveu, não da erro apenas não envia o email.

2020-10-20 14:14 UTC, mtslucasmartins approved these changes

2020-10-20 14:14 UTC, merged